application: humming-bird
version: 1
runtime: python
api_version: 1

handlers:

- url: /sitemap
  static_dir: sitemap

- url: /tool
  static_dir: tool

- url: /youtube_search
  script: /youtube_search.py

- url: /youtube_results
  script: youtube_results.py

- url: /.*
  script: main.py
